config/routes.rb
RailsPlay::Application.routes.draw do

  resources :users

  match '/roteador/dlink524/filtros' => 'network_router#control_mac_filters'

  root :to => 'network_router#control_mac_filters'

end

app/models/user.rb
class User < ActiveRecord::Base

	#------------------------------
	def full_name
		"#{first_name} #{last_name}"
	end

	#------------------------------
	def academic_full_name
		"#{last_name}, #{first_name}"
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  protect_from_forgery

  before_filter :get_router_model_and_version


  #------------------------------
  def get_router_model_and_version(options = {})
    @router_model = nil

    @_i_get_how_this_works = false

    # TODO: I need to study how this works...
    # Get the firmware version
    # (I'm thinking in making with an access througth web interface using nokogiri or something like web automating test to do it - its the quickly and easy way)
    case @_i_get_how_this_works
    when true
      raise AwesomeError, "Awesome! Go programing now!"
    when false
      @router_model = :DLink524
      @router_version = '2.07'
    end

    @router_model_and_version = "#{@router_model} v#{@router_version}"
  end

end

app/controllers/network_router_controller.rb
class NetworkRouterController < ApplicationController

	#------------------------------
	# Interface to control router filters
	def control_mac_filters
		case @router_model
		when :DLink524 # Firmware version 2.07
			# The 'options' are the same HTML element (<input type="RADIO" name="_EF">)
			# and has no way to select one if not by selecting by the index of the element:
			# [0] - Disabled MAC Filters
			# [1] - Only allow computers with MAC address listed below to access the network
			# !!!NEVER USE THIS!!! # [2] - Only deny computers with MAC address listed below to access the network # !!!NEVER USE THIS!!! # - This is especifically for my case :)
			@mac_filter_url = 'http://192.168.0.1/pmac.htm'
			option_mac_disable = 0
			@option_mac_enable = 1
			# @option_mac_disable_all = 2
		else
			raise StandardError, 'No other Router configured yet.'
		end

		#...
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  #------------------------------
  def index
    @users = User.all
    respond_with(@users)
  end

  #------------------------------
  def show
    @user = User.find(params[:id])
    respond_with(@user)
  end

  #------------------------------
  def new
    @user = User.new
    respond_with(@user)
  end

  #------------------------------
  def edit
    @user = User.find(params[:id])
    respond_with(@user)
  end

  #------------------------------
  def create
    @user = User.new(params[:user])
    respond_with(@user)
  end

  #------------------------------
  def update
    @user = User.find(params[:id])
    respond_with(@user)
  end

  #------------------------------
  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to users_path
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper

	#------------------------------
  def full_current_domain_url
    "#{request.protocol}#{request.host_with_port}"
  end

  #------------------------------
  def full_current_domain_url_with_fullpath
    "#{full_current_domain_url}#{request.fullpath}"
  end

end

app/helpers/network_router_helper.rb
module NetworkRouterHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!--[if lt IE 7]>      <html lang="<%= I18n.locale %>" class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html lang="<%= I18n.locale %>" class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html lang="<%= I18n.locale %>" class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html lang="<%= I18n.locale %>" class="no-js"> <!--<![endif]-->
	<head>
		<meta charset="utf-8">
		<meta http-equiv="content-style-type" content="text/css" />
		<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

		<meta name="viewport" content="width=device-width,initial-scale=1">
		
		<meta name="SKYPE_TOOLBAR" content="SKYPE_TOOLBAR_PARSER_COMPATIBLE" /> 
		
		<!-- <base href="<%= full_current_domain_url %>" /> -->
		
		<title>RailsPlay</title>
		
		<meta name="keywords" content="">
		<meta name="description" content="">

		<%= stylesheet_link_tag "application", :media => "all" %>
		<%= stylesheet_link_tag "dijit/themes/soria/soria", :media => "screen" %>

		<%= csrf_meta_tags %>

		<script>
		var dojoConfig = {
			has: {
        "dojo-firebug": true,
        "dojo-debug-messages": true
      },
			parseOnLoad: true,
			async: true,
			baseUrl: 'assets/dojo/',
      cacheBust: true // Get "fresh" resources
		};
		</script>

		<!--//
		Env: <%= Rails.env %> 
		Controller: <%= controller.controller_name %>
		Action: <%= controller.action_name %>
		//-->

		<%= javascript_include_tag "application" %>

		<script>
		// APPHTML-0#000001
		require(["dojo/i18n!dijit/form/nls/validate", "dojo/on", "dojo/ready", "dojo/json", "dojo/_base/config",
			"dojo/parser", "dijit/registry", "dijit/form/Button", "dojo/domReady!"],
		function(i18n, on, ready, JSON, config, parser, registry, button) {
			console.info('APPHTML-0#000001'); //debug
			ready(function() {
				parser.parse();
				var dialog = registry.byId("dialog");
				// dialog.set("content", "<pre>" + JSON.stringify(config, true) + "</pre>");
				dialog.show();
			});
		});
		</script>

	</head>
	<body class="soria" data-controller="<%= controller_name %>" data-action="<%= action_name %>">

		<!--[if lt IE 7]>
			<p class="chromeframe">You are using an outdated browser. <a href="http://browsehappy.com/">Upgrade your browser today</a> or <a href="http://www.google.com/chromeframe/?redirect=true">install Google Chrome Frame</a> to better experience this site.</p>
		<![endif]-->

		<div id="main-container" class="container">

			<%= yield %>

			<div data-dojo-type="dijit/Dialog" id="dialog" title="Tip" class="align-center">
			   <p>Enable the 'console' if you want to see the debug info.</p>
			   <p></p>
			   <p>PRESS ESC TO EXIT THIS DIALOG</p>
			</div>

			<br/>

			<hr>

			<footer>
				<p><strong><em>RailsPlay</em></strong> &copy; 2012</p>
			</footer>

		</div><!-- /container -->

	</body>
</html>

app/views/network_router/control_mac_filters.html.erb
<div>
	<h1>Control MAC Filters</h1>

	<h3>Router Model/Version: <%= @router_model_and_version %></h3>
</div>

<div class="">

    <div class="">
    	<button id="enableMACFilterBtn" data-dojo-type="dijit/form/Button" type="button">Enable MAC Filters</button>
    </div>

    <div class="">
    	<button id="disableMACFilterBtn" data-dojo-type="dijit/form/Button" type="button">Disable MAC Filters</button>
    </div>
    
</div>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br />
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br />
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :website %><br />
    <%= f.text_field :website %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>First name</th>
    <th>Last name</th>
    <th>Email</th>
    <th>Website</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.first_name %></td>
    <td><%= user.last_name %></td>
    <td><%= user.email %></td>
    <td><%= user.website %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>First name:</b>
  <%= @user.first_name %>
</p>

<p>
  <b>Last name:</b>
  <%= @user.last_name %>
</p>

<p>
  <b>Email:</b>
  <%= @user.email %>
</p>

<p>
  <b>Website:</b>
  <%= @user.website %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>